# =============================================================================
# Приложения. Каждое в своём подкаталоге со своим CMakeLists.txt
#
#   bench   запуск любого алгоритма с замером метрик (нужны сторонние библиотеки)
# =============================================================================
if(YAGKP_BUILD_BENCHMARK)
    add_subdirectory(bench)
endif()